# Taps
tap 'buo/cask-upgrade' #cask for upgrade-cli
tap 'teamookla/speedtest'
tap 'github/gh'
tap 'adoptopenjdk/openjdk'

# Speedtest
brew 'speedtest'

# Shells
brew 'zsh'

# Binaries
brew 'awscli'
brew 'gh'
brew 'git'
brew 'mas'
brew 'nvm'
brew 'python'
cask 'adoptopenjdk8'
cask 'adoptopenjdk13'

# Apps
cask 'alacritty'
cask 'adobe-creative-cloud'
cask 'discord'
cask 'docker'
cask 'github'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'hyper'
cask 'iina'
cask 'imageoptim'
cask 'java'
cask 'jetbrains-toolbox'
cask 'keka'
cask 'plex-media-player'
cask 'steam'
cask 'tower'
cask 'transmission'
cask 'transmit'
cask 'whatsapp'
cask 'visual-studio-code'
cask 'openemu'
cask 'transmission'
cask 'imagealpha'

# Quicklook
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklookase'
cask 'suspicious-package'

# Install Mac App Store apps
mas 'Pages', id: 409201541
mas 'Xcode', id: 497799835
